
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzdumgvhdqnmcbunqjnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZHVtZ3ZoZHFubWNidW5xam5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTgwMjgsImV4cCI6MjA2MTc5NDAyOH0.9XC8tjPkdF6aLwYX-OmVWS2NmO2vw1m1WRKTmi0Ake8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
